apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: datadog-apm-enabler
webhooks:
- name: admissioncontrol.datadog.com-apm-enabler
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  clientConfig:
    service:
      namespace: default
      name: datadog-admission-controller
      path: /
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVGRENDQXZ3Q0NRQ2xhN3RBMTFsUmxEQU5CZ2txaGtpRzl3MEJBUTBGQURDQnl6RUxNQWtHQTFVRUJoTUMKVlZNeEN6QUpCZ05WQkFnTUFrTkJNUkV3RHdZRFZRUUhEQWhRWlhSaGJIVnRZVEVPTUF3R0ExVUVFUXdGT1RRNQpOVEl4SFRBYkJnTlZCQWtNRkRJeE1EQWdVeUJOWTBSdmQyVnNiQ0JDYkhaa01Sc3dHUVlEVlFRS0RCSlpaM0psCmJtVWdSVzVsY21kNUlFWjFibVF4RkRBU0JnTlZCQXNNQzBWdVoybHVaV1Z5YVc1bk1STXdFUVlEVlFRRERBcDUKWjNKbGJtVXVZMjl0TVNVd0l3WUpLb1pJaHZjTkFRa0JGaFo2WVdOb0xtRnlibTlzWkVCNVozSmxibVV1WTI5dApNQjRYRFRFNU1ESXhOVEE1TlRnd00xb1hEVEU1TURNeE56QTVOVGd3TTFvd2djc3hDekFKQmdOVkJBWVRBbFZUCk1Rc3dDUVlEVlFRSURBSkRRVEVSTUE4R0ExVUVCd3dJVUdWMFlXeDFiV0V4RGpBTUJnTlZCQkVNQlRrME9UVXkKTVIwd0d3WURWUVFKREJReU1UQXdJRk1nVFdORWIzZGxiR3dnUW14MlpERWJNQmtHQTFVRUNnd1NXV2R5Wlc1bApJRVZ1WlhKbmVTQkdkVzVrTVJRd0VnWURWUVFMREF0RmJtZHBibVZsY21sdVp6RVRNQkVHQTFVRUF3d0tlV2R5ClpXNWxMbU52YlRFbE1DTUdDU3FHU0liM0RRRUpBUllXZW1GamFDNWhjbTV2YkdSQWVXZHlaVzVsTG1OdmJUQ0MKQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0NBUW9DZ2dFQkFNRlU1dGY0OC9ZV0Z1YVo3bHc3MUlHegpVbWZqblRSWGN6Q3FYYXRaTVNLSUtDY1U1Y1ZRTlZBM0ZzblduRVRwMmNhUCtqU2JmZ1hLeUx5RVVhU2lRYWlECk4zWkgrMEh6bmEwMjliUXdOMWVJVE8rcmFvdnpnMXZQS2MzWkgrMGVsNTVxckNZL2dKcEZweVV1dFJLa3F0SXYKeXFjSjhMZWowRVdSUUh2TlY3V3VCSGI1b2ViVDVtaEpvK3dGQm5ueUh3WmVvWXBIWGFjU1FIQjd6aFdlNVgwcApGZkRrc05TL29yZFdYejFMZndHbHIvM3U5alpINTVSZUt4Y0RlRDJuY3F0dFBqU011NnpWR0RGakpSWFZGcmZkCjJPVmtoM1k3NHMyeUFJdGdwWDZCRGNVTkJaSWNVT3dhSUFMWlRkUHIyOTVMeVRUWW1ERnlNcEpQTWlRdHN3MEMKQXdFQUFUQU5CZ2txaGtpRzl3MEJBUTBGQUFPQ0FRRUFqUUVrRTZjMmxCYXpCbE00OGVRTkJQQmNWT09MalYrdwpZZEtiNjIrZEpNaUtjSUtDSXhJc1pKcng2MTA3UEpYSVUxTElsS2RhNVFQKzUzaXB1SG52M051Ty95L3hIL01CCldXUjZxVlFZbTFTVG1sVWNFdHlrVlFEcmNWcXlRUmh6WkVScTBXTXFrUEhrVzlGUDVQMXFobzhoUFVWejVPV1EKY1I1Q2JVc3cxUXdETlAzb0RBeHFrdnJ1aWhRcmVpK0dsWFN6cFNHdnhhUWRUQWp1WXQ0czJCU0RXdWkwbGU0WgpSbEhVMmNMbzEyVVQ3VTRCWUpvRG4rWk11aEdlbk9PY2tSOTI0S2RHY1NKQkRCV3pQU1c2d1VJUXFreFNudVJJClRIajZsbFdZTEhHcHRZUGZ3ZncvRW1HdHE4RTY5Z2M5WGJ1aG5LZ01TMmNtcG0zZFhlLzZsQT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K