kind: ServiceAccount
apiVersion: v1
metadata:
  name: dd-admission-controller-sa
  namespace: default
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dd-admission-controller-clusterrole
  namespace: default
rules:
- apiGroups: ["extensions", "apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods", "namespaces"]
  verbs: ["get", "list"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: dd-admission-controller-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: dd-admission-controller-sa
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: dd-admission-controller-clusterrole